name: "DevReplay test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
jobs:
  devreplay:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install devreplay
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: echo "::add-matcher::.github/devreplay-match.json"   
      - name: Run devreplay
        run: node_modules/.bin/devreplay --dir ./src devreplay.json